# -*- coding: utf-8 -*-
"""ML_clinical_1st_20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shbYrrLFcoB8zt3lxwOAv9hHs5LvZnrr
"""

import pandas as pd

# === Step 1: Load Files ===
clinical_df = pd.read_csv("/content/clin_for_ML.csv")             # Contains: sample, age, stage, gender
expression_df = pd.read_csv("/content/Z_scaling_THCA_data_1.csv")         # Contains: sample, GENE1...GENE231009, os_time

# === Step 2: Select 20 Genes ===
# Replace with your actual 20 gene names
selected_genes = [
    'ESRRB','LOC389705','GRM3','FLJ39582','C1orf168','PHYHIPL','PPIAL4D','ELOVL3','TMPRSS5','CXADRP3','SRMS','C7orf13','PCDHGB3','FAM153A','TH','LOC100133669','TMEM26','TCP11','STC1','HSD17B14'
]

expression_df

# Columns to keep from expression data
columns_to_keep = ['sample', 'OS_time'] + selected_genes
expression_df = expression_df[columns_to_keep]

# === Step 3: Clean Clinical Data ===
# Drop rows with missing or zero values
clinical_df = clinical_df.dropna(subset=['age', 'gender', 'stage'])
clinical_df = clinical_df[~clinical_df[['age', 'gender', 'stage']].isin([0, '0']).any(axis=1)]

# Encode gender: FEMALE = 0, MALE = 1
clinical_df['gender'] = clinical_df['gender'].str.upper().str.strip()
clinical_df['Gender'] = clinical_df['gender'].map({'FEMALE': 0, 'MALE': 1})

# Encode stage: I=0, II=1, III=2, IV/IVA/IVC=3
stage_mapping = {
    'STAGE I': 0, 'STAGE II': 1, 'STAGE III': 2,
    'STAGE IV': 3, 'STAGE IVA': 3, 'STAGE IVB': 3, 'STAGE IVC': 3
}
clinical_df['stage'] = clinical_df['stage'].str.upper().str.strip()
clinical_df['Stage'] = clinical_df['stage'].map(stage_mapping)

# === Step 4: Merge Clinical + Expression Data ===
merged_df = pd.merge(expression_df, clinical_df[['sample', 'age', 'Gender', 'Stage']],
                     on='sample', how='inner')

# === Step 5: Final Clean-Up ===
merged_df = merged_df.dropna()  # Drop any remaining NaNs

# === Step 6: Output ===
print("Final merged shape:", merged_df.shape)
print(merged_df.head())

# Save final dataset for ML
merged_df.to_csv("final_20_genes_with_clinical_and_os.csv", index=False)

merged_df

# === Step 5: Final Clean-Up ===
merged_df = merged_df.dropna()

# Move 'os_time' column to the last
cols = [col for col in merged_df.columns if col != 'OS_time'] + ['OS_time']
merged_df = merged_df[cols]

# === Step 6: Output ===
print("Final merged shape:", merged_df.shape)
print(merged_df.head())

# Save final dataset
merged_df.to_csv("final_20_genes_with_clinical_and_os.csv", index=False)

# Remove the first column using iloc
df = merged_df.iloc[:, 1:]

print("DataFrame after removing the first column using iloc:")
print(df)

# Sort the DataFrame by the os_time column in ascending order
df_sorted = df.sort_values(by='OS_time', ascending=True).reset_index(drop=True)

# Display the sorted DataFrame
print(df_sorted)

df_sorted = df_sorted[df_sorted['OS_time'] > 0]


df_sorted

# Step 2: Define a function to map OS_in_days to classes
def map_os_class(OS_time):
    years = OS_time / 365.25  # Convert days to years
    if years <= 1:
        return 0  # 0-1 year
    elif years <= 3:
        return 1  # 1-3 years
    elif years <= 5:
        return 2  # 3-5 years
    else:
        return 3  # more than 5 years

# Step 3: Create OS class column for training and independent DataFrames
df_sorted['os_class'] = df_sorted['OS_time'].apply(map_os_class)

from imblearn.over_sampling import SMOTE
# Separate the target variable and the rest of the data
X = df_sorted.drop(['os_class','OS_time'], axis=1)
y = df_sorted['os_class']
# Apply SMOTE to oversample the minority class
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X, y)
# Print the class distribution before and after SMOTE
print("Class distribution before SMOTE:")
print(y.value_counts())
print("Class distribution after SMOTE:")
print(y_resampled.value_counts())
# Update X and y with the resampled data
X = X_resampled
y = y_resampled
# Create a new DataFrame with the resampled data
SMOTEDdf = pd.concat([X, y], axis=1)
SMOTEDdf

# Step 1: Split the dataset into training and testing
training_sets = []
independent_sets = []

for i in range(0, len(SMOTEDdf), 5):
    independent_set = SMOTEDdf.iloc[i:i + 1]  # Select the i-th row for testing
    training_set = SMOTEDdf.iloc[i + 1:i + 5]  # Select the next 4 rows for training

    if not independent_set.empty:
        independent_sets.append(independent_set)

    if not training_set.empty:
        training_sets.append(training_set)

# Combine the training and independent sets into DataFrames
independent_df = pd.concat(independent_sets, ignore_index=True)
training_df = pd.concat(training_sets, ignore_index=True)

# Step 2: Reshuffle both the training and independent datasets
training_df = training_df.sample(frac=1, random_state=42).reset_index(drop=True)
independent_df = independent_df.sample(frac=1, random_state=42).reset_index(drop=True)

training_df

independent_df

# Save DataFrame to CSV
training_df.to_csv('training_df_1st_clin.csv', index=False)
# Save DataFrame to CSV
independent_df.to_csv('independent_df_1st_clin.csv', index=False)



from sklearn.preprocessing import StandardScaler

# Step 1: Separate features and target
X_train = training_df.drop(columns='os_class')
y_train = training_df['os_class']

X_test = independent_df.drop(columns='os_class')
y_test = independent_df['os_class']

# Step 2: Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 3: Rename arrays as required
X_train_selected = X_train_scaled
X_test_selected = X_test_scaled

# Now you have:
# X_train_selected: scaled training features
# X_test_selected: scaled test features
# y_train: training target (os_time)
# y_test: test target (os_time)

# Check shapes
print("X_train_selected shape:", X_train_selected.shape)
print("X_test_selected shape:", X_test_selected.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier  # Import XGBoost
from sklearn.metrics import (accuracy_score, confusion_matrix, roc_auc_score,
                             classification_report, cohen_kappa_score,
                             matthews_corrcoef, precision_score, recall_score)
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
import lightgbm as lgb
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier


# Define classifiers including AdaBoost and CatBoost
classifiers = {
  'Random Forest': RandomForestClassifier(random_state=42, n_estimators=1000, max_depth=11, min_samples_split=6, min_samples_leaf=3),
    'SVM': SVC(probability=True, random_state=42, C=10, kernel='rbf', gamma='auto'),
    'Extra Trees': ExtraTreesClassifier(random_state=42, n_estimators=500, bootstrap=True, min_samples_split=3),
    'XGBoost': XGBClassifier(random_state=42, n_estimators=500, max_depth=10, min_child_weight=5, reg_alpha=1, reg_lambda=1),
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'LightGBM': lgb.LGBMClassifier(random_state=42, n_estimators=500, max_depth=10, min_child_samples=20),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42, n_estimators=500, max_depth=10),
    'Naive Bayes': GaussianNB(),
    'MLP': MLPClassifier(hidden_layer_sizes=(50,), max_iter=1000, random_state=42),
    #'AdaBoost': AdaBoostClassifier(random_state=42, n_estimators=500),
    #'CatBoost': CatBoostClassifier(random_state=42, iterations=800, depth=12, learning_rate=0.2, cat_features=[], verbose=1)
    }


# Prepare for results
results = []


# Stratified Cross-Validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Loop over each classifier
for model_name, model in classifiers.items():
    acc_train_list = []
    auc_train_list = []
    sens_train_list = []
    spec_train_list = []
    mcc_train_list = []
    kappa_train_list = []

    # Cross-validation loop
    for train_index, val_index in cv.split(X_train_selected, y_train):
        X_cv_train, X_cv_val = X_train_selected[train_index], X_train_selected[val_index]
        y_cv_train, y_cv_val = y_train.iloc[train_index], y_train.iloc[val_index]

        # Train the model
        model.fit(X_cv_train, y_cv_train)

        # Predictions
        y_cv_val_pred = model.predict(X_cv_val)
        y_cv_val_prob = model.predict_proba(X_cv_val)

        # Metrics
        acc_train = accuracy_score(y_cv_val, y_cv_val_pred)
        auc_train = roc_auc_score(y_cv_val, y_cv_val_prob, multi_class='ovr')
        sens_train = recall_score(y_cv_val, y_cv_val_pred, average='weighted')
        spec_train = precision_score(y_cv_val, y_cv_val_pred, average='weighted')
        mcc_train = matthews_corrcoef(y_cv_val, y_cv_val_pred)
        kappa_train = cohen_kappa_score(y_cv_val, y_cv_val_pred)

        # Store metrics
        acc_train_list.append(acc_train)
        auc_train_list.append(auc_train)
        sens_train_list.append(sens_train)
        spec_train_list.append(spec_train)
        mcc_train_list.append(mcc_train)
        kappa_train_list.append(kappa_train)

    # Average metrics for training
    results.append({
        'Model': model_name,
        'Train Accuracy': np.mean(acc_train_list),
        'Train AUC': np.mean(auc_train_list),
        'Train Sensitivity': np.mean(sens_train_list),
        'Train Specificity': np.mean(spec_train_list),
        'Train MCC': np.mean(mcc_train_list),
        'Train Kappa': np.mean(kappa_train_list),
    })

    # Test the model on independent test set
    model.fit(X_train_selected, y_train)
    y_test_pred = model.predict(X_test_selected)
    y_test_prob = model.predict_proba(X_test_selected)

    # Test metrics
    acc_test = accuracy_score(y_test, y_test_pred)
    auc_test = roc_auc_score(y_test, y_test_prob, multi_class='ovr')
    sens_test = recall_score(y_test, y_test_pred, average='weighted')
    spec_test = precision_score(y_test, y_test_pred, average='weighted')
    mcc_test = matthews_corrcoef(y_test, y_test_pred)
    kappa_test = cohen_kappa_score(y_test, y_test_pred)

    # Add testing metrics to results
    results[-1].update({
        'Test Accuracy': acc_test,
        'Test AUC': auc_test,
        'Test Sensitivity': sens_test,
        'Test Specificity': spec_test,
        'Test MCC': mcc_test,
        'Test Kappa': kappa_test,
    })

# Convert results to DataFrame and display
results = pd.DataFrame(results)
print(results)

from google.colab import files

# Save results_df to a CSV file
results.to_csv('1st_results_clinical_20_genes.csv', index=False)

from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
import matplotlib.pyplot as plt
from google.colab import files

# Get the best model (based on some metric like Test AUC)
best_model_name = results.loc[results['Test AUC'].idxmax(), 'Model']
best_model = classifiers[best_model_name]

# Predictions for the test set
y_test_prob = best_model.predict_proba(X_test_selected)

# Binarize the true labels
y_test_binarized = label_binarize(y_test, classes=[0, 1, 2, 3])

# Plot the ROC curve for each class
plt.figure(figsize=(10, 8))
for i in range(y_test_binarized.shape[1]):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_test_prob[:, i])
    auc_score = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {auc_score:.2f})')

# Plot the diagonal line representing a random classifier
plt.plot([0, 1], [0, 1], 'k--', label='Random Classifier')

# Add labels and title
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title(f'ROC Curve - Best Model ({best_model_name})')
plt.legend(loc='lower right')
plt.grid(True)

# Save the plot before showing it
plt.savefig('auc_plot.png', dpi=300, bbox_inches='tight')

# Display the plot
plt.show()

# Download the saved plot
files.download('auc_plot.png')