# -*- coding: utf-8 -*-
"""Thyroid_Cancer_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYG3gsFzDgZA0YQx2AO-pkgSF6kWDjja
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive/Thyroid_cancer_dataset/

file_path = "/content/drive/MyDrive/Thyroid_cancer_dataset"

file_path

import pandas as pd
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Specify the file path (without extension for now)
file_path = "/content/drive/MyDrive/Thyroid_cancer_dataset/TCGA_THCA.csv"

# 1. Check if the file exists
import os
if os.path.exists(file_path):
  print(f"File found at: {file_path}")
else:
  print(f"Error: File not found at: {file_path}")
  print("Please double-check the file path.")
  # Exit if file not found to prevent further errors
  # You can remove this exit and proceed to step 2 for further diagnosis
  # but it's likely there's an issue with the file path if it's not found
  import sys
  sys.exit(1)

# 2. Try to open and read a few lines to inspect its format
try:
  with open(file_path, 'r') as f:
    for i in range(5): # Print first 5 lines
      print(f.readline().strip())
except Exception as e:
  print(f"Error opening or reading the file: {e}")

# Based on the output of the above, you can then try:
# - pd.read_csv(file_path, sep="\t") if it looks like a tab-separated file
# - pd.read_csv(file_path, sep=",") if it looks like a comma-separated file
# - Or use other appropriate pandas functions based on the file format
#   (e.g., pd.read_excel, pd.read_json, etc.)

df = pd.read_csv(file_path, sep=",")  # Comma-separated format
print(df.head())

df

# Assuming 'df' is your Pandas DataFrame
transposed_df = df.transpose()

transposed_df

# Set the first row as column names and transpose the DataFrame
transposed_df.columns = transposed_df.iloc[0]

transposed_df

transposed_df= transposed_df.iloc[1:]

transposed_df

## count number of zeroes per gene ##
count = (transposed_df == 0).sum()
count

m = 473/2
m

##find how many zeroes are less than half number of genes#
(count <= m)

############### remove less than 50% zeroes value genes ####################
a =[]
for i in transposed_df.columns:
    if ((transposed_df[i] == 0).sum() < m):
        a.append(transposed_df[i])

############ convert a into dataframe and than transpose file #########
df1 = pd.DataFrame(a).T
df1

from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold = 0.25)
selector.fit(df1)
feature_indices = selector.get_support(indices = True)
df2 = df1.iloc[:, feature_indices]
df2

df2

df2.to_csv("After_preprocessing_THCA_data.csv", index=True)

## Preprocessing#

## ADD survival data

import pandas as pd
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Specify the file path (without extension for now)
file_path = "/content/drive/MyDrive/Thyroid_cancer_dataset/survival_THCA_survival.txt"

import os

file_path = "/content/drive/MyDrive/Thyroid_cancer_dataset/survival_THCA_survival.txt"

if os.path.exists(file_path):
    print("✅ File found!")
else:
    print("❌ File NOT found! Check the path.")

!head /content/drive/MyDrive/Thyroid_cancer_dataset/survival_THCA_survival.txt

import pandas as pd

# Read the tab-separated file without the 'index' argument
df3 = pd.read_csv(file_path, sep="\t")

# If you need to reset the index:
df3 = df3.reset_index(drop=True)

# Show first few rows
print(df3.head())

df3

df3_cleaned = df3.drop(columns=["Redaction", "DSS", "DSS.time","OS","DFI","DFI.time","PFI","PFI.time","_PATIENT"])
df3_cleaned

df3_cleaned = df3_cleaned.rename(columns={"OS.time": "OS_time"})

df3_cleaned

df3_cleaned = df3_cleaned.set_index("sample")

df3_cleaned

df_merged = df3_cleaned.merge(df2, on="sample", how="inner")  # Keeps only matching samples

df_merged

# Move "OS_time" to the last position
cols = [col for col in df_merged.columns if col != "OS_time"]  # Get all columns except "OS_time"
df_merged = df_merged[cols + ["OS_time"]]  # Append "OS_time" at the end

df_merged

df_merged.to_csv("merging_os_THCA_data.csv", index=True)

import pandas as pd
import numpy as np
# Identify columns to apply log2 normalization (all except OS_time)
genes = [col for col in df_merged.columns if col != "OS_time"]

# Extract expression data only
df_expres= df_merged[genes]

# Keep OS_time separately
df_surv = df_merged[["OS_time"]]

df_log2 = np.log2(df_expres + 1)  # log2(x + 1) transformation

df_final_norm = pd.concat([df_log2, df_surv], axis=1)

print(df_final_norm.head())  # Check first few rows
print(df_final_norm.describe())  # Check transformed distribution

df_final_norm.to_csv("log2_norm_THCA_data.csv", index=True)

## Z-scaling##

import pandas as pd
from sklearn.preprocessing import StandardScaler


# Identify columns to scale (all except OS_time)
genes = [col for col in df_final_norm.columns if col != "OS_time"]

# Extract expression data only
df_expression = df_final_norm[genes]

# Keep OS_time separately
df_survival = df_final_norm[["OS_time"]]
scaler = StandardScaler()

# Apply Z-score scaling
df_scaled = pd.DataFrame(scaler.fit_transform(df_expression), index=df_expression.index, columns=df_expression.columns)

df_final = pd.concat([df_scaled, df_survival], axis=1)

print(df_final.head())  # Check first few rows
print(df_final.describe())  # Mean should be ~0, std ~1 for genes

df_final

df_final.to_csv("Z_scaling_THCA_data.csv", index=True) ## done##